import { readdirSync, readFileSync, writeFileSync, mkdirSync, statSync } from 'node:fs'
import { join, relative, parse } from 'node:path'

interface IconInfo {
  name: string
  category: string
  viewBox: string
  width: number
  height: number
  colors: string[]
  colorCount: number
  hasMultipleColors: boolean
}

function extractViewBox(svgContent: string): string {
  const viewBoxMatch = svgContent.match(/viewBox=["']([^"']+)["']/)
  return viewBoxMatch ? viewBoxMatch[1] : '0 0 24 24'
}

function parseViewBox(viewBox: string): { width: number; height: number } {
  const parts = viewBox.split(/\s+/)
  return {
    width: parseFloat(parts[2] || '24'),
    height: parseFloat(parts[3] || '24')
  }
}

function extractColors(svgContent: string): string[] {
  const colors = new Set<string>()

  const fillMatches = svgContent.matchAll(/fill=["']([^"']+)["']/g)
  for (const match of fillMatches) {
    const color = match[1]
    if (color && color !== 'none' && color !== 'currentColor') {
      colors.add(color)
    }
  }

  const strokeMatches = svgContent.matchAll(/stroke=["']([^"']+)["']/g)
  for (const match of strokeMatches) {
    const color = match[1]
    if (color && color !== 'none' && color !== 'currentColor') {
      colors.add(color)
    }
  }

  return Array.from(colors)
}

function scanIconDirectory(dir: string, baseDir: string = dir): IconInfo[] {
  const icons: IconInfo[] = []
  const entries = readdirSync(dir)

  for (const entry of entries) {
    const fullPath = join(dir, entry)
    const stat = statSync(fullPath)

    if (stat.isDirectory()) {
      icons.push(...scanIconDirectory(fullPath, baseDir))
    } else if (entry.endsWith('.svg')) {
      try {
        const svgContent = readFileSync(fullPath, 'utf-8')
        const relativePath = relative(baseDir, fullPath)
        const { dir: categoryPath, name: fileName } = parse(relativePath)

        const category = categoryPath || 'default'
        const iconName = category ? `${category}/${fileName}` : fileName

        const viewBox = extractViewBox(svgContent)
        const { width, height } = parseViewBox(viewBox)
        const colors = extractColors(svgContent)
        const colorCount = colors.length
        const hasMultipleColors = colorCount > 1

        icons.push({
          name: iconName,
          category,
          viewBox,
          width,
          height,
          colors,
          colorCount,
          hasMultipleColors
        })
      } catch (error) {
        console.warn(`Warning: Failed to process ${fullPath}:`, error)
      }
    }
  }

  return icons
}

export async function generateTypes(iconsDir: string, outputDir: string): Promise<number> {
  const icons = scanIconDirectory(iconsDir)
  const sortedIcons = icons.sort((a, b) => a.name.localeCompare(b.name))
  const categories = Array.from(new Set(icons.map(icon => icon.category))).sort()

  const iconNames = sortedIcons.map(icon => `  | '${icon.name}'`).join('\n')
  const iconCategories = categories.map(cat => `  | '${cat}'`).join('\n')

  const iconMetadataEntries = sortedIcons.map(icon => {
    return `  '${icon.name}': {
    name: '${icon.name}',
    category: '${icon.category}',
    viewBox: '${icon.viewBox}',
    width: ${icon.width},
    height: ${icon.height},
    hasMultipleColors: ${icon.hasMultipleColors},
    colorCount: ${icon.colorCount}
  }`
  }).join(',\n')

  const iconNamesArray = sortedIcons.map(icon => `  '${icon.name}'`).join(',\n')

  const iconCategoriesEntries = categories.map(category => {
    const categoryIcons = sortedIcons
      .filter(icon => icon.category === category)
      .map(icon => `'${icon.name}'`)
      .join(', ')
    return `  '${category}': [${categoryIcons}]`
  }).join(',\n')

  const fileContent = `/**
 * THIS IS A GENERATED FILE. DO NOT EDIT!
 * Сгенерировано автоматически. Не редактировать вручную!
 *
 * Generated by: @rovik/vue-svg-icons
 * Total icons: ${sortedIcons.length}
 * Categories: ${categories.length}
 */

export type IconCategory =
${iconCategories};

export type IconName =
${iconNames};

export interface IconMetadata {
  name: IconName;
  category: IconCategory;
  viewBox: string;
  width: number;
  height: number;
  hasMultipleColors: boolean;
  colorCount: number;
}

export const ICON_METADATA: Record<IconName, IconMetadata> = {
${iconMetadataEntries}
};

export const ICON_NAMES = [
${iconNamesArray}
] as const;

export const ICON_CATEGORIES: Record<IconCategory, readonly IconName[]> = {
${iconCategoriesEntries}
};
`

  mkdirSync(outputDir, { recursive: true })
  writeFileSync(join(outputDir, 'types.ts'), fileContent, 'utf-8')

  return sortedIcons.length
}
